language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t juanparblo/react-test-image  ./client

script:
  - docker run -e CI=false juanparblo/react-test-image npm run test -- -- coverage 
  

after_success:
  - docker build -t juanparblo/multi-client   ./client
  - docker build -t juanparblo/multi-server   ./server
  - docker build -t juanparblo/multi-nginx    ./nginx
  - docker build -t juanparblo/multi-worker   ./worker

  ## Log in to dockerhun via the cli
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin

  ## push the docker images to docker hub (docker registry)
  - docker push juanparblo/multi-client
  - docker push juanparblo/multi-server
  - docker push juanparblo/multi-nginx
  - docker push juanparblo/multi-worker 

#deploy:
# on:
#  push:
#    branch: 
#     - master
  ## - feature
# pull_request:
# provider: 'elasticbeanstalk'
# region: 'us-east-1'
# app: 'Multi-container-app'
 #env:
 #bucket_name:
 #bucket_path:
 #access_key_id: $AWS_KEY_ID
 #secret_access_key: 
 #   secure: $AWS_SECRET_KEY
