version: '3'
serivces:  
   nginx:
     image: juanparblo/muulti-client
     restart: always
     host: image
     ports:
      - 80:80
     depends_on:
      - client
      - api  
     mem_limit: 128m
       

   server:
     image: juanparblo/multi-server
     restart: 'unless_stopped'
     host: api
     environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
       



   worker:
     image: juanparblo/multi-worker
     restart: 'on_failure'
     host: worker
     mem_limit: 128m
     environment:
       - REDIS_HOST=$REDIS-host
       - REDIS_PORT=$REDIS_PORT



   client:
     image: juanparblo/multi-client
     restart: 'no'





 